// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhdmfxbogaxepchnxhnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZG1meGJvZ2F4ZXBjaG54aG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MDUyNDAsImV4cCI6MjA4ODI4MTI0MH0.MLKW5hXpC6Jv5-UlwGkVe_-VL8vySg1Ffv9-spPoJ8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});